### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by anhnguyenbkcsna**
Update expo 16 to 18 and related package (already remove package-lock.json)

### CODE REVIEW

**Comment by anhnguyenbkcsna** [comment]
I wonder that there is 2 commits in my update branch of forked repo like that, if you accept this pull request, will they merge changes from 2 commits or only the latest change?

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by hoanglehaithanh** [comment]
@anhnguyenbkcsna The number of commits does not affect the final result after merging your request.

**Review by hoanglehaithanh — APPROVED** [review]
LGTM. Approved and Testing on simulation.

**Comment by hoanglehaithanh** [comment]
@anhnguyenbkcsna Next time you should write a more detailed title while submitting Pull Request. Example: `Upgrade Expo to the latest version (48) and other dependencies)`

**Pull request merged**
